buildrun:
	mkdir -p bin/
	gcc -g -o bin/client.out -lm -Wall client.c -lncurses
	./bin/client.out

build:
	mkdir -p bin/
	gcc -g -o bin/client.out -lm -Wall client.c -lncurses

run:
	./bin/client.out

clean:
	rm -r -f bin/

