buildrun:
	mkdir -p bin/
	gcc -g -o bin/client.out -lm -lncurses -Wall client.c
	./bin/client.out

build:
	mkdir -p bin/
	gcc -g -o bin/client.out -lm -lncurses -Wall client.c

run:
	./bin/client.out

clean:
	rm -r -f bin/

