buildrun:
	mkdir -p bin/
	gcc -g -o bin/client.out -Wall client.c -lm -lncurses
	./bin/client.out

build:
	mkdir -p bin/
	gcc -g -o bin/client.out -Wall client.c -lm -lncurses

run:
	./bin/client.out

clean:
	rm -r -f bin/
